- packer/builder/azure/utils/BuildContainerName.go
Discovered that the code would not even build due to an import that was left after removing the code that depended on it.
> Bugfix for "make temporary container name random"

- packer/builder/azure/driver_restapi/subcriptionManagement.go
Otherwise when the binary copied to vanilla debian it fails withe following:
$ packer build -var sn=mysubs -var psPath=./my.publishsettings packer-azure.json
==> azure: Preparing builder...
azure: Getting subscr info...
Build 'azure' errored: ParsePublishSettings error: user: Current not implemented on linux/amd64
> replace os/user with github.com/mitchellh/go-homedir to avoid the use of cgo

- .travis.yml
> only use known go versions

- packer/builder/azure/driver_restapi/builder.go
- packer/builder/azure/driver_restapi/request/AddCertificate.go
- packer/builder/azure/driver_restapi/request/AddOSImage.go
- packer/builder/azure/driver_restapi/request/CaptureVMImage.go
- packer/builder/azure/driver_restapi/request/CheckStorageAccountNameAvailability.go
- packer/builder/azure/driver_restapi/request/CreateCloudService.go
- packer/builder/azure/driver_restapi/request/CreateVMImage.go
- packer/builder/azure/driver_restapi/request/CreateVirtualMachineDeployment.go
- packer/builder/azure/driver_restapi/request/DeleteCloudService.go
- packer/builder/azure/driver_restapi/request/DeleteDeployment.go
- packer/builder/azure/driver_restapi/request/DeleteDisk.go
- packer/builder/azure/driver_restapi/request/DeleteRole.go
- packer/builder/azure/driver_restapi/request/GetDeployment.go
- packer/builder/azure/driver_restapi/request/GetOperationStatus.go
- packer/builder/azure/driver_restapi/request/GetOperationStatus_test.go
- packer/builder/azure/driver_restapi/request/GetOsImages.go
- packer/builder/azure/driver_restapi/request/GetStorageAccountKeys.go
- packer/builder/azure/driver_restapi/request/GetVmImages.go
- packer/builder/azure/driver_restapi/request/ListResourceExtensions.go
- packer/builder/azure/driver_restapi/request/ListServiceCertificates.go
- packer/builder/azure/driver_restapi/request/RetryPolicy.go
- packer/builder/azure/driver_restapi/request/ShutdownRoles.go
- packer/builder/azure/driver_restapi/request/UpdateRole.go
- packer/builder/azure/driver_restapi/request/manager.go
- packer/builder/azure/driver_restapi/request/subcriptionManagement.go
- packer/builder/azure/driver_restapi/request_tests/init.go
- packer/builder/azure/driver_restapi/response/model/AzureError.go
- packer/builder/azure/driver_restapi/response/model/Operation.go
Removed separate 'driver' concept, collapsed it into the 'manager' object.
Changed from io.Reader to []byte for carrying the request payloads.
Use same api version for all requests.
Fixes #24 
Fixes #25
cc: @ahmetalpbalkan @Snesha @jeffmendoza
> Add retry logic for Azure service management operations

- .travis.yml
Use gox to cross compile and github releases to store the binaries for tagged commits
> Deploy tagged commits to github releases

- README.md
- packer/builder/azure/driver_restapi/constants/clientType.go
- packer/builder/azure/driver_restapi/request/subcriptionManagement.go
This should provide the basic support for building and running packer on a Mac OSX dev box as mentioned in Issue #44. I added the documentation for building, and removed the table in the README as it was 1) hard to copy/paste, and the scrolling of the table was a bit annoying.
> Add MacOSX Dev Box Support

- packer/builder/azure/driver_restapi/targets/step_poll_status.go
Fixes #59
Port is read as a string from the XML, so format string also needs to expect a string.
I broke this in 5ff6eda :frowning:... sorry about that
Signed-off-by: Paul Meyer <paul.meyer@microsoft.com>
> Change ip/port format back to %s:%s

- packer/builder/azure/driver_restapi/targets/step_create_image.go
Just fixing a typo, trying to make print statement a bit clearer
> Fix typo in packer-azure output

- packer/builder/azure/driver_restapi/request/CreateVirtualMachineDeployment.go
DisableSshPasswordAuthentication=true cannot be undone by redeploy: https://github.com/Azure/WALinuxAgent/blob/ddfe7821580842f6f2de1a9ee2c68629bd26a5bf/waagent#L4441-L4447
Fixes #62 
cc: @ahmetalpbalkan
> Fix password authentication

- packer/builder/azure/builder.go
- packer/builder/azure/config.go
- packer/builder/azure/win/step_set_provision_infrastructure.go
- packer/communicator/azureVmCustomScriptExtension/communicator.go
Fix #52 by introducing new config parameter "provision_timeout_in_minutes" with default value of 120 (2 hours). Value of "0" disables timeout entirely.
> Long running extensionSettings time out, even if they are still running on the host #52 

- packer/communicator/azureVmCustomScriptExtension/communicator.go
* To get rid of 512-bytes alignment (that's a limitation of page blobs)
* To upload big files (> 32MB), which is usually required to install some serious software on Windows
> Upload files to block blob storage instead of page blob

- packer/builder/azure/constants/stateBag.go
- packer/builder/azure/win/step_set_provision_infrastructure.go
- packer/communicator/azureVmCustomScriptExtension/communicator.go
It fails on https://github.com/MSOpenTech/packer-azure/blob/86e4e8392d07bf123c55dfe4e769a9878bfaee24/packer/builder/azure/win/step_set_provision_infrastructure.go#L71 otherwise
> Drop unused IsOSImage variable in stateBag

- config_examples/packer-azure_CentOS.json
- packer/builder/azure/step_validate.go
Issue #62 regressed when adopting the Azure SDK for Go, this re-fixes this issue.
> Fix regression of DisableSSHPasswordAuthentication

- packer/builder/azure/arm/deployment_poller_test.go
packer/builder/azure/arm/deployment_poller_test.go:33: possible formatting directive in Fatal call
packer/builder/azure/arm/deployment_poller_test.go:47: possible formatting directive in Fatal call
packer/builder/azure/arm/deployment_poller_test.go:61: possible formatting directive in Fatal call
packer/builder/azure/arm/deployment_poller_test.go:83: unreachable code
packer/builder/azure/arm/deployment_poller_test.go:88: possible formatting directive in Fatal call
> Fix go vet issues.

- packer/builder/azure/arm/step_validate_template.go
- packer/builder/azure/arm/step_validate_template_test.go
- packer/builder/azure/common/constants/stateBag.go
As it turns out IsValid is not valid. :stuck_out_tongue_closed_eyes: 
This addresses #157.
> Remove the state bag property IsValid.

- packer/builder/azure/arm/config.go
- packer/builder/azure/arm/config_test.go
This allows users to override configuration such as SSHTimeout,
WinRMTimeout, etc.
This PR fixes issue #166.
> Import packer's configuration directly.

- packer/builder/azure/arm/config_test.go
By slowly removing elements we can ensure that each element is in fact
required for success.
This addresses issue #164.
> Slowly remove instead of add.

- packer/builder/azure/smapi/FindImage.go
- packer/builder/azure/smapi/config.go
- packer/builder/azure/smapi/config_test.go
- packer/builder/azure/smapi/step_validate.go
The proposed code adds a parameter os_image_name to be used instead of os_image_label. 
It allows to precise the name of the source image either : 
- as listed in "azure vm image list", ie the hermetic [32chars id]__[human_readble_name]
- or only the last part of the name [human_readble_name]
depending on what you prefer to copy paste or read. 
For instance : 
```
"os_image_name": "Ubuntu-14_04_3-LTS-amd64-server-20150805-en-us-30GB"
"os_image_name": "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20150805-en-us-30GB"
```
It should solve the issue #108 as the user can more easily find the name of the OS he is looking for, and implements the #131 .
> New parameter os_image_name

- config_examples/arm/CentOS_7.1.json
- config_examples/arm/OpenSuSE_13.2.json
- config_examples/arm/README.md
- config_examples/arm/debian_8.json
- config_examples/arm/ubuntu_14.04.3-LTS.json
- config_examples/packer-azure_Debian.json
- packer/builder/azure/arm/builder.go
- packer/builder/azure/arm/config.go
- packer/builder/azure/arm/config_test.go
Clean up some of the existing templates, and make them more useful (and work).
Move the OS generalize step to the provisioner because the provisioner knows how to execute a remote command, but a Communicator does not necessarily.
Cleanup up some uses of username, ssh_username, password, ssh_password, and ensure that precedence when overriding is treated appropriately.
> Move OS Generalize to Provisioner

- packer/builder/azure/arm/builder.go
There was a build break because the go-autorest changed the way Service
Principal Tokens (SPT) are created.  The API is now explicit about how an
OAuth token is formulated, and the endpoints used.  The code hardcodes to
Azure's public cloud.  We are no worse than we were because we still did not
support US Government Cloud and China.  There is already a pending issue
to address this.
> Handle API update to better handle OAuth.

- packer/builder/azure/common/lin/step_create_cert.go
- packer/builder/azure/smapi/step_create_vm.go
Signed-off-by: John Howard <jhoward@microsoft.com>
Fixed some case consistencies on output messages, and corrected `Polling till temp...` to Polling `until`...
> Fix case consistency and 'till'

- config_examples/arm/ubuntu_14.04.4-LTS.json
- config_examples/arm/ubuntu_14.04.4-LTS_quickstart.json
This should save a few minutes when deploying Ubuntu because the number of
updates is much less.  The mirrors will thank me too.
> Update latest Ubuntu 14.04 version.

- config_examples/arm/CentOS_7.2.json
- packer/builder/azure/arm/config.go
- packer/builder/azure/arm/config_test.go
- packer/builder/azure/arm/template.go
- packer/builder/azure/arm/template_parameters.go
The image version used to default to latest, which made reproducible
builds difficult if the image version changed frequently, or if regions
did not have the same latest version.
> Allow the user to set the image version.

- packer/builder/azure/arm/step.go
- packer/builder/azure/arm/step_capture_image.go
- packer/builder/azure/arm/step_create_resource_group.go
- packer/builder/azure/arm/step_delete_os_disk.go
- packer/builder/azure/arm/step_delete_resource_group.go
- packer/builder/azure/arm/step_deploy_template.go
- packer/builder/azure/arm/step_power_off_compute.go
- packer/builder/azure/arm/step_test.go
- packer/builder/azure/arm/step_validate_template.go
- packer/builder/azure/common/interruptible_task.go
- packer/builder/azure/common/interruptible_task_test.go
- packer/builder/azure/common/state_bag.go
Fix for #141.
If a user hits Ctrl-C the user will have to wait until the step has
completed before the Ctrl-C is processed.  This change processes the
Ctrl-C within a 100ms, and immediately aborts all work.  There is no
cleanup done, and the task running in Azure is not killed.  The following
tasks are now interruptible.
* capture image
* delete resource group
* deploy template
* power off
All othere tasks run quickly enough that I did not make them
interruptible.
Small refactoring to the way errors are handled at the end of each step.
> Support interrupting long running tasks.

- packer/builder/azure/arm/azure_client.go
- packer/builder/azure/arm/builder.go
- packer/builder/azure/arm/inspector.go
- packer/builder/azure/arm/openssh_key_pair_test.go
- packer/builder/azure/common/logutil/logfields.go
The body is currently captured because it contains valuable information.
The downside is that the body is very big, and makes very noisy logs.  I'm
not sure if the happy medium is not to log the body because without it
diagnosing failures is very difficult.
> Log Azure requests and responses.

- packer/builder/azure/arm/artifact.go
- packer/builder/azure/arm/artifact_test.go
- packer/builder/azure/arm/azure_client.go
- packer/builder/azure/arm/builder.go
- packer/builder/azure/arm/capture_template.go
- packer/builder/azure/arm/capture_template_test.go
- packer/builder/azure/arm/inspector.go
- packer/builder/azure/arm/step_capture_image.go
- packer/builder/azure/arm/step_capture_image_test.go
- packer/builder/azure/common/constants/stateBag.go
- packer/builder/azure/common/interruptible_task.go
The artifact now includes the following data.
* storage account location
* storage account blob name
* URL of the packer VHD
* read-only SAS URL of the packer VHD that's good for about 30 days
* URL of a template to deploy the VHD
* read-only SAS URL of a template to deploy the VHD that's good for about
30 days
> Output a reasonable artifact.

- packer/builder/azure/smapi/builder.go
- packer/builder/azure/smapi/config.go
- packer/builder/azure/smapi/step_set_provision_infrastructure.go
- packer/builder/azure/smapi/step_validate.go
- packer/communicator/azureVmCustomScriptExtension/communicator.go
… and use it everywhere.
Non-public cloud provisioning for Windows machines was broken because in two places storage clients were being created with default base uri (core.windows.net).
cc: @boumenot @mbearup
> Create storage client during online config validation
