Azure/packer-azure

.travis.yml, README.md, packer/builder/azure/driver_restapi/installer/main_test.go, packer/builder/azure/driver_restapi/request_tests/AddOSImage_test.go, packer/builder/azure/driver_restapi/request_tests/AvailabilityResponse_test.go, packer/builder/azure/driver_restapi/request_tests/CaptireVmImage_test.go, packer/builder/azure/driver_restapi/request_tests/CreateVirtualMachineDeployment_test.go, packer/builder/azure/driver_restapi/request_tests/CreateVmImage_test.go, packer/builder/azure/driver_restapi/request_tests/GetDeploymet_test.go, packer/builder/azure/driver_restapi/request_tests/GetOsImages_test.go, packer/builder/azure/driver_restapi/request_tests/GetStorageAccountKeys_test.go, packer/builder/azure/driver_restapi/request_tests/GetVmImages_test.go, packer/builder/azure/driver_restapi/request_tests/ListResourceExtensions_test.go, packer/builder/azure/driver_restapi/request_tests/ListServiceCertificates_test.go, packer/builder/azure/driver_restapi/request_tests/ShutdownRoles_test.go, packer/builder/azure/driver_restapi/request_tests/UpdateRoleResourceExtensionReference_test.go, packer/builder/azure/driver_restapi/request_tests/init.go, packer/builder/azure/driver_restapi/storage_tests/GetContainerSAS_test.go, packer/builder/azure/driver_restapi/utils/string_test.go
After merging this pull request, someone with admin access to the repo should enable this repo on http://travis-ci.org . Note that I added a build badge to the readme ([![Build Status](https://travis-ci.org/paulmey/packer-azure.svg?branch=travis-ci)](https://travis-ci.org/paulmey/packer-azure)), but this won't show anything until travis actually starts building commits.
cc: @ahmetalpbalkan
=> Add Travis-CI

packer/builder/azure/driver_restapi/request/GetOperationStatus.go, packer/builder/azure/driver_restapi/request/GetOperationStatus_test.go
These tests fail sometimes. I'm assuminig that it's a timing issue.
=> Give the WaitForOperation tests a little bit more time

config_examples/packer-azure_CentOS.json, config_examples/packer-azure_OpenSUSE.json, config_examples/packer-azure_Ubuntu_serv14.json, config_examples/packer-azure_Win2012r2.json, config_examples/packer-azure_Win2012r2_inet.json
Central US is easier accessible for our integration tests
=> move examples from West US to Central US

packer/builder/azure/driver_restapi/request_tests/AddOSImage_test.go, packer/builder/azure/driver_restapi/request_tests/CaptureVmImage_test.go, packer/builder/azure/driver_restapi/request_tests/CreateVmImage_test.go, packer/builder/azure/driver_restapi/targets/step_create_image.go
=> Fix some typos 'paker' -> 'packer'

packer/builder/azure/driver_restapi/builder.go, packer/builder/azure/driver_restapi/requestlogger.go
Sometimes necessary for debugging.
=> Add optional Azure HTTP request logging

packer/builder/azure/driver_restapi/builder.go, packer/builder/azure/driver_restapi/config.go, packer/builder/azure/driver_restapi/constants/stateBag.go, packer/builder/azure/driver_restapi/targets/lin/ssh.go, packer/builder/azure/driver_restapi/targets/step_poll_status.go
Along the same lines as https://github.com/mitchellh/packer/commit/e55792811967d9c90367a8f92d9b60b79497055c
=> Switch ssh connect step for Packer 0.8.0

packer/builder/azure/builder.go, packer/builder/azure/config.go
=> Make user name configureable

packer/builder/azure/retry/operations.go
=> Detect correct error type for retries

packer/builder/azure/config.go, packer/builder/azure/config_test.go, packer/builder/azure/step_validate.go
=> Allow remote image deployment

packer/builder/azure/config.go, packer/builder/azure/config_test.go, packer/builder/azure/step_validate.go
fixes #66 
@ahmetalpbalkan please review
=> add data disks

packer/communicator/azureVmCustomScriptExtension/communicator.go, packer/provisioner/azureVmCustomScriptExtension/provisioner.go
One of the dependencies, in this case uuid has been moved to a new location so I updated it.
=> Updated uuid source

packer/builder/azure/retry/operations.go, packer/builder/azure/retry/retrypolicy.go, packer/builder/azure/retry/retrypolicy_test.go
=> Fix wrong type assertion for recognizing errors that need retries

packer/builder/azure/retry/operations.go
Fixes #102. Verified with some integration testing.
=> Fix error detection

packer/builder/azure/FindImage.go, packer/builder/azure/builder.go, packer/builder/azure/retry/operations.go, packer/builder/azure/step_create_image.go, packer/builder/azure/step_validate.go
cc: @boumenot, @ahmetalpbalkan
=> Fixes after sdk updates

packer/builder/azure/FindImage.go, packer/builder/azure/FindImage_test.go
After some testing I found this rather sad bug I introduced in the past...
=> Fix user image matching

packer/builder/azure/step_validate.go
Apparently, MediaLink needs to be left empty for user images. Opened a PR in SDK to make this knowledge knowable from vmutils package.
=> Fix user image deployment

packer/builder/azure/step_validate.go
The Azure SDK just merged a fix to distguish between Azure provided,
and user created images.
=> Fix build break.

packer/builder/azure/arm/deployment_factory.go, packer/builder/azure/arm/deployment_factory_test.go
A deployment combines a template and the template's parameters, and
submits the whole thing to Azure for processing.
=> Factory to create a deployment.

packer/builder/azure/arm/deployment_poller.go, packer/builder/azure/arm/deployment_poller_test.go
=> Implement deployment poller.

packer/builder/azure/arm/step_validate_template.go, packer/builder/azure/arm/step_validate_template_test.go
=> Implement validate template step.

packer/builder/azure/arm/step_query_vm.go, packer/builder/azure/arm/step_query_vm_test.go
=> Implement query VM step.

packer/builder/azure/arm/step_power_off_compute.go, packer/builder/azure/arm/step_power_off_compute_test.go
=> Implement power off compute.

packer/builder/azure/arm/step_delete_resource_group.go, packer/builder/azure/arm/step_delete_resource_group_test.go
=> Implement delete resource group step.

packer/builder/azure/arm/step_deploy_template.go, packer/builder/azure/arm/step_deploy_template_test.go
=> Implement deploy template step.

packer/builder/azure/arm/step_capture_image.go, packer/builder/azure/arm/step_capture_image_test.go
=> Implement capture image step.

packer/builder/azure/arm/step_delete_os_disk.go, packer/builder/azure/arm/step_delete_os_disk_test.go
=> Implement delete OS disk step.

packer/builder/azure/arm/step_capture_image_test.go, packer/builder/azure/arm/step_create_resource_group_test.go, packer/builder/azure/arm/step_delete_os_disk_test.go, packer/builder/azure/arm/step_delete_resource_group_test.go, packer/builder/azure/arm/step_deploy_template_test.go, packer/builder/azure/arm/step_get_ip_address_test.go, packer/builder/azure/arm/step_get_os_disk_test.go, packer/builder/azure/arm/step_power_off_compute_test.go, packer/builder/azure/arm/step_validate_template_test.go
Remove all instances of Validate for Step.  This addresses issue #162.
=> Scrub test case name.

packer/builder/azure/arm/builder.go
=> Correctly handle errors.

config_examples/arm/CentOS_7.1.json, config_examples/arm/OpenSuSE_13.2.json, config_examples/arm/README.md, config_examples/arm/debian_8.json, config_examples/arm/ubuntu_14.04.3-LTS.json, packer/builder/azure/arm/README.md
Start of documentation for ARM to get you started.
=> README for ARM

packer/builder/azure/arm/builder.go
Right now when provision fails, or build is cancelled, oacker still reports as successfull:
```
2016/02/06 08:53:07 ui error: ==> azure-arm: Deployment failed with a status of 'Failed'.
==> azure-arm: Deployment failed with a status of 'Failed'.
2016/02/06 08:53:07 ui:     azure-arm: after run
azure-arm: after run
2016/02/06 08:53:07 ui error: ==> azure-arm: Deployment failed with a status of 'Failed'.
==> azure-arm: Deployment failed with a status of 'Failed'.
2016/02/06 08:53:07 ui: Build 'azure-arm' finished.
Build 'azure-arm' finished.
2016/02/06 08:53:07 Builds completed. Waiting on interrupt barrier...
2016/02/06 08:53:07 ui: 
==> Builds finished. The artifacts of successful builds are:
2016/02/06 08:53:07 machine readable: azure-arm,artifact-count []string{"1"}
==> Builds finished. …
```
=> Error handling for arm builder

packer/builder/azure/arm/builder.go, packer/builder/azure/arm/config.go
=> Custom ssh auth

packer/communicator/azureVmCustomScriptExtension/communicator.go
=> Add missing new interface method

.travis.yml
Fix the conditionals used in the build.
=> Fix code coverage conditionals.

packer/builder/azure/smapi/artifact.go, packer/builder/azure/smapi/artifact_test.go, packer/builder/azure/smapi/builder.go, packer/builder/azure/smapi/check_test.go, packer/builder/azure/smapi/requestlogger.go, packer/plugin/packer-post-processor-azure-sm-vhdonly/main.go, packer/post-processor/azure-sm-vhdonly/post-processor.go, packer/post-processor/azure-sm-vhdonly/post-processor_test.go
=> Add post-processor to leave only VHD

packer/builder/azure/arm/azure_client.go, packer/builder/azure/arm/builder.go, packer/builder/azure/arm/builder_test.go, packer/builder/azure/arm/config.go, packer/builder/azure/arm/config_test.go, packer/builder/azure/arm/deployment_factory_test.go, packer/builder/azure/arm/step_get_os_disk_test.go, packer/builder/azure/arm/template.go, packer/builder/azure/arm/template_parameters.go, packer/builder/azure/arm/template_parameters_test.go, packer/builder/azure/common/constants/stateBag.go
=> Add support for US Government and China Clouds

packer/builder/azure/arm/inspector.go
I forgot to implement Paul's suggestion. :frowning:
=> Ensure the body is closed.

config_examples/packer-azure_Debian.json, config_examples/packer-azure_OpenSUSE.json, config_examples/packer-azure_Win2012r2.json, config_examples/packer-azure_Win2012r2_inet.json
updating a bunch to be able to run these in CI
=> Fix SM examples

.travis.yml
The issues wasn't in the build script, it was in the UI where the
environment variables were being set.  Somewhere between the UI and the
builder the variables were being zeroed out, and the fix is to quote them.
=> Revert to the originl .travis.yml.

packer/builder/azure/smapi/config.go, packer/builder/azure/smapi/step_validate.go
=> move location checking to validate step and check available sizes

packer/builder/azure/smapi/step_validate.go
=> Fix storage account location error message
